[build.environment]
  NODE_VERSION = "18"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/101-prompt-engineering/*"
  to = "/101-prompt-engineering/index.html"
  status = 200

[[redirects]]
  from = "/102-openai-api/*"
  to = "/102-openai-api/index.html"
  status = 200

[[redirects]]
  from = "/201-langchain-modules/*"
  to = "/201-langchain-modules/index.html"
  status = 200

[[redirects]]
  from = "/202-langchain-chains/*"
  to = "/202-langchain-chains/index.html"
  status = 200

[[redirects]]
  from = "/203-langchain-agents/*"
  to = "/203-langchain-agents/index.html"
  status = 200

[[redirects]]
  from = "/301-langchain-chatdoc/*"
  to = "/301-langchain-chatdoc/index.html"
  status = 200

[[redirects]]
  from = "/302-langserve/*"
  to = "/302-langserve/index.html"
  status = 200

[[redirects]]
  from = "/240106-langchain-status/*"
  to = "/240106-langchain-status/index.html"
  status = 200

[[redirects]]
  from = "/240720-langchain-minio/*"
  to = "/240720-langchain-minio/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://github.com/webup/agi-talks"
  status = 302
  force = true