[build.environment]
  NODE_VERSION = "18"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/101-prompt-engineering/*"
  to = "/101-prompt-engineering/index.html"
  status = 200

[[redirects]]
  from = "/102-openai-api/*"
  to = "/102-openai-api/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://github.com/webup/agi-talks"
  status = 302
  force = true